openapi: 3.0.3
info:
  title: Quiz
  version: 1.0.0
  description: API for quiz questions
servers:
  - url: https://quiz-express-57b839d4ea17.herokuapp.com
    description: Production server
paths:
  /api/quiz-questions/:
    get:
      operationId: quiz_questions_list
      parameters:
      - in: query
        name: quiz_name
        schema:
          type: string
      tags:
      - quiz-questions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuizQuestion'
          description: ''
    post:
      operationId: quiz_questions_create
      tags:
      - quiz-questions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizQuestion'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizQuestion'
          description: ''
  /api/quiz-questions/{id}/:
    get:
      operationId: quiz_questions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz question.
        required: true
      tags:
      - quiz-questions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizQuestion'
          description: ''
    put:
      operationId: quiz_questions_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz question.
        required: true
      tags:
      - quiz-questions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizQuestion'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizQuestion'
          description: ''
    patch:
      operationId: quiz_questions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz question.
        required: true
      tags:
      - quiz-questions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedQuizQuestion'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizQuestion'
          description: ''
    delete:
      operationId: quiz_questions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz question.
        required: true
      tags:
      - quiz-questions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/quizzes/:
    get:
      operationId: quizzes_list
      tags:
      - quizzes
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
          description: ''
    post:
      operationId: quizzes_create
      tags:
      - quizzes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          description: ''
  /api/quizzes/{id}/:
    get:
      operationId: quizzes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz.
        required: true
      tags:
      - quizzes
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          description: ''
    put:
      operationId: quizzes_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz.
        required: true
      tags:
      - quizzes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          description: ''
    patch:
      operationId: quizzes_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz.
        required: true
      tags:
      - quizzes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedQuiz'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          description: ''
    delete:
      operationId: quizzes_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quiz.
        required: true
      tags:
      - quizzes
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    PatchedQuiz:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
    PatchedQuizQuestion:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        quiz_name:
          type: string
          readOnly: true
        question:
          type: string
          maxLength: 255
        answer_1:
          type: string
          maxLength: 255
        answer_2:
          type: string
          nullable: true
          maxLength: 255
        answer_3:
          type: string
          nullable: true
          maxLength: 255
        answer_4:
          type: string
          nullable: true
          maxLength: 255
        correct_answer:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        additional_info:
          type: string
          nullable: true
        difficulty_level:
          type: integer
          nullable: true
        quiz:
          type: integer
    Quiz:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    QuizQuestion:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        quiz_name:
          type: string
          readOnly: true
        question:
          type: string
          maxLength: 255
        answer_1:
          type: string
          maxLength: 255
        answer_2:
          type: string
          nullable: true
          maxLength: 255
        answer_3:
          type: string
          nullable: true
          maxLength: 255
        answer_4:
          type: string
          nullable: true
          maxLength: 255
        correct_answer:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        additional_info:
          type: string
          nullable: true
        difficulty_level:
          type: integer
          nullable: true
        quiz:
          type: integer
      required:
      - answer_1
      - correct_answer
      - id
      - question
      - quiz
      - quiz_name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
